version: '3.3'

services:
  icecreamdatabasev3:
    build: .
    container_name: IceCreamDataBaseV3
    #env_file:
    #  - .env
    #network_mode: bridge
    #extra_hosts:
    #  - "host.docker.internal:host-gateway"
    #volumes:
    #  - /var/run/mysqld/mysqld.sock:/root/mysqld.sock:rw
    networks:
      - mariadbnetwork
    restart: unless-stopped

networks:
  mariadbnetwork:
    name: "mariadbnetwork"
    external: true
